-- AlterTable
ALTER TABLE "Request" ALTER COLUMN "valorRequest" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "valorDescount" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "tax" SET DATA TYPE DOUBLE PRECISION;
